# Generated by Django 2.0.6 on 2018-07-02 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minutetalk', '0003_auto_20180702_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=30, null=True)),
                ('img_src', models.FileField(default='channels/nopic.jpg', upload_to='channels/')),
                ('title', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
