# Generated by Django 2.0.6 on 2018-07-02 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minutetalk', '0005_auto_20180702_1923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_name',
        ),
    ]
