# Generated by Django 2.0.6 on 2018-07-03 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minutetalk', '0008_channeltype'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='channel_type',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='minutetalk.ChannelType'),
            preserve_default=False,
        ),
    ]
