# Generated by Django 2.0.6 on 2018-07-06 10:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('minutetalk', '0010_channeluser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channeluser',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='channeluser',
            name='user',
        ),
        migrations.AddField(
            model_name='channel',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ChannelUser',
        ),
    ]
