# Generated by Django 2.0.6 on 2018-07-06 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minutetalk', '0011_auto_20180706_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='users',
            field=models.ManyToManyField(to='minutetalk.UserProfile'),
        ),
    ]
