# Generated by Django 2.0.6 on 2018-07-06 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minutetalk', '0012_auto_20180706_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='users',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='channels',
            field=models.ManyToManyField(to='minutetalk.Channel'),
        ),
    ]
