# Generated by Django 2.0.6 on 2018-07-06 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minutetalk', '0013_auto_20180706_1826'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='channels',
            new_name='channel',
        ),
    ]
