# Generated by Django 2.0.6 on 2018-07-06 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minutetalk', '0014_auto_20180706_1832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='channel',
            new_name='channels',
        ),
    ]
