# Generated by Django 2.0.6 on 2018-07-06 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minutetalk', '0015_auto_20180706_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
