# Generated by Django 2.0.6 on 2018-07-10 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minutetalk', '0017_auto_20180709_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channeluser',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='channeluser',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='channels',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='fav_channels',
            field=models.ManyToManyField(related_name='fav_channels', to='minutetalk.Channel'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='my_channel',
            field=models.ForeignKey(default=31, on_delete=django.db.models.deletion.CASCADE, related_name='current_channels', to='minutetalk.Channel'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ChannelUser',
        ),
    ]
