# Generated by Django 2.0.6 on 2018-07-10 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minutetalk', '0018_auto_20180710_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='fav_channels',
            field=models.ManyToManyField(to='minutetalk.Channel'),
        ),
    ]
