# Generated by Django 2.0.6 on 2018-07-10 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minutetalk', '0019_auto_20180710_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='my_channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_channel', to='minutetalk.Channel'),
        ),
    ]
