# Generated by Django 2.0.6 on 2018-07-10 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minutetalk', '0020_auto_20180710_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='fav_channels',
            field=models.ManyToManyField(null=True, to='minutetalk.Channel'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='my_channel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_channel', to='minutetalk.Channel'),
        ),
    ]
