# Generated by Django 2.0.6 on 2018-07-11 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minutetalk', '0021_auto_20180710_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='img_src',
            field=models.ImageField(default='users/noprof.jpg', upload_to='users/'),
        ),
    ]
