# Generated by Django 2.0.6 on 2018-07-12 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minutetalk', '0023_callercallee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='fav_channels',
            field=models.ManyToManyField(blank=True, null=True, to='minutetalk.Channel'),
        ),
    ]
