# Generated by Django 2.0.6 on 2018-07-12 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minutetalk', '0024_auto_20180712_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='callercallee',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
