# Generated by Django 2.0.6 on 2018-07-16 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('minutetalk', '0025_callercallee_accepted'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=400)),
                ('session_id', models.CharField(blank=True, max_length=72)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='callercallee',
            name='callee',
        ),
        migrations.RemoveField(
            model_name='callercallee',
            name='caller',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='my_channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_channel', to='minutetalk.Channel'),
        ),
        migrations.DeleteModel(
            name='CallerCallee',
        ),
    ]
