# Generated by Django 2.0.6 on 2018-07-17 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minutetalk', '0027_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='channel_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='minutetalk.ChannelType'),
        ),
    ]
