# Generated by Django 2.0.6 on 2018-07-18 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minutetalk', '0029_auto_20180717_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='url',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
