# Generated by Django 2.0.6 on 2018-07-19 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minutetalk', '0031_auto_20180719_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='description',
            field=models.CharField(max_length=900, null=True),
        ),
    ]
