# Generated by Django 2.0.6 on 2018-07-19 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minutetalk', '0032_auto_20180719_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='title',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
