# Generated by Django 2.0.6 on 2018-07-19 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minutetalk', '0033_auto_20180719_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
