# Generated by Django 2.0.7 on 2018-07-19 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minutetalk', '0034_channel_featured'),
        ('minutetalk', '0031_payment'),
    ]

    operations = [
    ]
